"use client";
import Link from "next/link";
import { Activity, ArrowRight, Building2, ShieldAlert, Siren, Users } from "lucide-react";
import { Metric } from "@/components/dashboard/metric";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Panel, PanelHeader } from "@/components/ui/panel";
import { PageHeading } from "@/components/ui/page-heading";
import { PageSkeleton } from "@/components/ui/skeleton";
import { useMockStore } from "@/lib/mock-store";
import { formatDateTime, isActiveStatus } from "@/lib/utils";
export default function AdminHome(){const{db,loading}=useMockStore();if(loading||!db)return <PageSkeleton/>;const active=db.requests.filter(r=>isActiveStatus(r.status)).length;const denied=db.auditLogs.filter(l=>l.result==="Denied").length;return <div className="app-page grid gap-5"><PageHeading eyebrow="Administration" title="System overview" description="Review mock platform activity, identities, organisations and security events."/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Users" value={db.users.length} detail="Across all roles" icon={<Users className="h-5 w-5"/>}/><Metric label="Organisations" value={db.organisations.length} detail="Configured response endpoints" icon={<Building2 className="h-5 w-5"/>}/><Metric label="Active requests" value={active} tone="danger" detail="Operational lifecycle" icon={<Siren className="h-5 w-5"/>}/><Metric label="Denied events" value={denied} tone="warning" detail="Security review" icon={<ShieldAlert className="h-5 w-5"/>}/></div><div className="grid gap-4 lg:grid-cols-2"><Panel><PanelHeader title="Latest audit activity" action={<Link href="/app/admin/audit"><Button variant="ghost" size="sm">View all<ArrowRight className="h-4 w-4"/></Button></Link>}/><div className="divide-y divide-[#e2e8ed]">{db.auditLogs.slice(0,6).map(log=><article key={log.id} className="p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{log.action}</h3><p className="mt-1 text-sm text-[#617582]">{log.actorName} · {log.target}</p><p className="mt-2 text-xs text-[#88969f]">{formatDateTime(log.timestamp)}</p></div><Badge tone={log.result==="Success"?"success":log.result==="Denied"?"danger":"warning"}>{log.result}</Badge></div></article>)}</div></Panel><Panel><PanelHeader title="Platform health" description="Mock configuration checks"/><div className="divide-y divide-[#e2e8ed]">{[{title:"Authentication",detail:"Mock JWT-like browser session",ok:true},{title:"Database",detail:"Browser localStorage demo store",ok:true},{title:"Hospital integration",detail:"Internal mock dispatch workflow",ok:false},{title:"Notifications",detail:"In-app lifecycle updates",ok:true}].map(item=><div key={item.title} className="flex items-center gap-3 p-4 sm:p-5"><span className={`h-2.5 w-2.5 rounded-full ${item.ok?"bg-[#1f845b]":"bg-[#b97018]"}`}/><div className="flex-1"><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm text-[#687b89]">{item.detail}</p></div><Activity className="h-4 w-4 text-[#8a9aa4]"/></div>)}</div></Panel></div></div>}
