"use client";
import { useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Select } from "@/components/ui/field";
import { Panel, PanelHeader } from "@/components/ui/panel";
import { PageHeading } from "@/components/ui/page-heading";
import { PageSkeleton } from "@/components/ui/skeleton";
import { useMockStore } from "@/lib/mock-store";
import { formatDateTime } from "@/lib/utils";
export default function AdminAudit(){const{db,loading}=useMockStore();const[filter,setFilter]=useState("All");if(loading||!db)return <PageSkeleton/>;const logs=db.auditLogs.filter(l=>filter==="All"||l.result===filter);return <div className="app-page grid gap-5"><PageHeading eyebrow="Administration" title="Audit trail" description="Structured security and operational events from the mock request lifecycle."/><Panel><PanelHeader title={`${logs.length} events`} action={<Select className="h-10 w-36" value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Success</option><option>Denied</option><option>Warning</option></Select>}/><div className="grid gap-3 p-3 md:hidden">{logs.map(log=><article key={log.id} className="rounded-2xl border border-[#dfe7ec] p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{log.action}</h2><p className="mt-1 text-xs text-[#71828d]">{formatDateTime(log.timestamp)}</p></div><Badge tone={log.result==="Success"?"success":log.result==="Denied"?"danger":"warning"}>{log.result}</Badge></div><dl className="mt-4 grid gap-3 border-t border-[#e2e8ed] pt-3 text-xs"><div><dt className="font-bold uppercase tracking-wide text-[#82919b]">Actor</dt><dd className="mt-1">{log.actorName} · {log.actorRole}</dd></div><div><dt className="font-bold uppercase tracking-wide text-[#82919b]">Target</dt><dd className="mt-1">{log.target}</dd></div><div><dt className="font-bold uppercase tracking-wide text-[#82919b]">Correlation</dt><dd className="mt-1 font-mono">{log.correlationId}</dd></div></dl></article>)}</div><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[950px] text-left text-sm"><thead className="border-y border-[#e2e8ed] bg-[#f7f9fa] text-xs uppercase tracking-wide text-[#70838f]"><tr><th className="px-5 py-3">Time</th><th className="px-5 py-3">Actor</th><th className="px-5 py-3">Action</th><th className="px-5 py-3">Target</th><th className="px-5 py-3">Correlation</th><th className="px-5 py-3">Result</th></tr></thead><tbody className="divide-y divide-[#e2e8ed]">{logs.map(log=><tr key={log.id}><td className="whitespace-nowrap px-5 py-4 text-xs text-[#71828d]">{formatDateTime(log.timestamp)}</td><td className="px-5 py-4"><p className="font-semibold">{log.actorName}</p><p className="text-xs text-[#71828d]">{log.actorRole}</p></td><td className="px-5 py-4"><p className="font-semibold">{log.action}</p><p className="text-xs text-[#71828d]">{log.metadata}</p></td><td className="px-5 py-4">{log.target}</td><td className="px-5 py-4 font-mono text-xs">{log.correlationId}</td><td className="px-5 py-4"><Badge tone={log.result==="Success"?"success":log.result==="Denied"?"danger":"warning"}>{log.result}</Badge></td></tr>)}</tbody></table></div></Panel></div>}
