import type {
  AuditLog,
  EmergencyRequest,
  MockDatabase,
  MockUser,
  Organisation,
  Responder,
} from "@/lib/types";

export interface MockCredential extends MockUser {
  password: string;
}

export const MOCK_CREDENTIALS: MockCredential[] = [
  {
    id: "usr-requester-001",
    name: "Thandi Mokoena",
    email: "requester@live.co.za",
    phone: "+27 82 555 0101",
    role: "requester",
    status: "Active",
    initials: "TM",
    emergencyContactName: "Sipho Mokoena",
    emergencyContactPhone: "+27 83 555 0110",
    password: "LiveUser123!",
  },
  {
    id: "usr-requester-006",
    name: "Neo Dube",
    email: "newrequester@live.co.za",
    phone: "+27 81 555 0166",
    role: "requester",
    status: "Active",
    initials: "ND",
    emergencyContactName: "Lerato Dube",
    emergencyContactPhone: "+27 82 555 0167",
    password: "LiveNewUser123!",
  },
  {
    id: "usr-dispatcher-001",
    name: "Naledi Dlamini",
    email: "dispatcher@live.co.za",
    phone: "+27 11 555 0102",
    role: "dispatcher",
    organisationId: "org-charlotte",
    status: "Active",
    initials: "ND",
    password: "LiveDispatch123!",
  },
  {
    id: "usr-responder-001",
    name: "Kabelo Nkosi",
    email: "responder@live.co.za",
    phone: "+27 72 555 0103",
    role: "responder",
    organisationId: "org-charlotte",
    status: "Active",
    initials: "KN",
    password: "LiveRespond123!",
  },
  {
    id: "usr-admin-001",
    name: "Ayesha Patel",
    email: "admin@live.co.za",
    phone: "+27 11 555 0104",
    role: "admin",
    organisationId: "org-live-admin",
    status: "Active",
    initials: "AP",
    password: "LiveAdmin123!",
  },
  {
    id: "usr-auditor-001",
    name: "Lerato Molefe",
    email: "auditor@live.co.za",
    phone: "+27 11 555 0105",
    role: "auditor",
    organisationId: "org-live-admin",
    status: "Active",
    initials: "LM",
    password: "LiveAudit123!",
  },
];

const organisations: Organisation[] = [
  {
    id: "org-charlotte",
    name: "Charlotte Maxeke Johannesburg Academic Hospital",
    type: "Hospital",
    serviceArea: "Johannesburg Central and surrounding districts",
    phone: "+27 11 488 4911",
    status: "Active",
    integration: "Mock dashboard",
  },
  {
    id: "org-netcare-milpark",
    name: "Milpark Emergency Response Unit",
    type: "Emergency response",
    serviceArea: "Parktown, Auckland Park and Braamfontein",
    phone: "+27 11 480 5600",
    status: "Active",
    integration: "Sandbox API",
  },
  {
    id: "org-live-admin",
    name: "LIVE Platform Operations",
    type: "Administration",
    serviceArea: "Platform-wide",
    phone: "+27 11 555 0199",
    status: "Active",
    integration: "Not configured",
  },
];

const responders: Responder[] = [
  {
    id: "rsp-001",
    userId: "usr-responder-001",
    name: "Kabelo Nkosi",
    team: "Rapid Response Alpha",
    vehicle: "Ambulance LIVE-21",
    phone: "+27 72 555 0103",
    organisationId: "org-charlotte",
    availability: "Assigned",
    location: { lat: -26.1866, lng: 28.0374 },
  },
  {
    id: "rsp-002",
    userId: "usr-responder-002",
    name: "Boitumelo Maseko",
    team: "Rapid Response Bravo",
    vehicle: "Ambulance LIVE-14",
    phone: "+27 73 555 0132",
    organisationId: "org-charlotte",
    availability: "Available",
    location: { lat: -26.1743, lng: 28.0417 },
  },
  {
    id: "rsp-003",
    userId: "usr-responder-003",
    name: "Jason Adams",
    team: "Medical Support Two",
    vehicle: "Response Unit LIVE-08",
    phone: "+27 74 555 0188",
    organisationId: "org-netcare-milpark",
    availability: "Available",
    location: { lat: -26.1809, lng: 28.0171 },
  },
  {
    id: "rsp-004",
    userId: "usr-responder-004",
    name: "Nomsa Khumalo",
    team: "Rapid Response Delta",
    vehicle: "Ambulance LIVE-32",
    phone: "+27 79 555 0144",
    organisationId: "org-charlotte",
    availability: "Offline",
    location: { lat: -26.2011, lng: 28.0456 },
  },
];

function isoMinutesAgo(minutes: number) {
  return new Date(Date.now() - minutes * 60_000).toISOString();
}

function history(
  requestId: string,
  entries: Array<[EmergencyRequest["status"], number, string, EmergencyRequest["statusHistory"][number]["actorRole"], string?]>,
) {
  return entries.map(([status, minutes, actorName, actorRole, note], index) => ({
    id: `${requestId}-history-${index + 1}`,
    status,
    timestamp: isoMinutesAgo(minutes),
    actorName,
    actorRole,
    note,
  }));
}

function createRequests(): EmergencyRequest[] {
  return [
    {
      id: "LIVE-20260804-1842",
      requesterId: "usr-requester-001",
      requesterName: "Thandi Mokoena",
      callbackNumber: "+27 82 555 0101",
      emergencyContact: "Sipho Mokoena · +27 83 555 0110",
      category: "Medical emergency",
      severity: "Critical",
      note: "Severe chest pain and difficulty breathing. Patient is conscious.",
      status: "En route",
      createdAt: isoMinutesAgo(18),
      updatedAt: isoMinutesAgo(2),
      location: {
        address: "22 Jorissen Street, Braamfontein, Johannesburg",
        lat: -26.1929,
        lng: 28.0305,
        accuracy: 18,
        capturedAt: isoMinutesAgo(18),
        method: "GPS",
      },
      organisationId: "org-charlotte",
      assignedResponderId: "rsp-001",
      etaMinutes: 7,
      operationalNotes: [
        "Dispatcher confirmed caller remains on the line.",
        "Response unit departed from Parktown staging point.",
      ],
      statusHistory: history("LIVE-20260804-1842", [
        ["Submitted", 18, "Thandi Mokoena", "requester", "Request submitted from mobile browser."],
        ["Received", 17, "LIVE routing", "system", "Request received by the dispatch queue."],
        ["Assigned", 13, "Naledi Dlamini", "dispatcher", "Assigned to Rapid Response Alpha."],
        ["En route", 10, "Kabelo Nkosi", "responder", "Responder departed; live tracking active."],
      ]),
    },
    {
      id: "LIVE-20260804-1768",
      requesterId: "usr-requester-002",
      requesterName: "Mpho Radebe",
      callbackNumber: "+27 82 555 0202",
      category: "Road incident",
      severity: "High",
      note: "Two-car collision. One person may have a leg injury.",
      status: "Assigned",
      createdAt: isoMinutesAgo(31),
      updatedAt: isoMinutesAgo(8),
      location: {
        address: "Empire Road near Jan Smuts Avenue, Johannesburg",
        lat: -26.1818,
        lng: 28.0269,
        accuracy: 28,
        capturedAt: isoMinutesAgo(31),
        method: "Map pin",
      },
      organisationId: "org-netcare-milpark",
      assignedResponderId: "rsp-003",
      etaMinutes: 11,
      operationalNotes: ["Traffic congestion reported on Empire Road."],
      statusHistory: history("LIVE-20260804-1768", [
        ["Submitted", 31, "Mpho Radebe", "requester"],
        ["Received", 29, "LIVE routing", "system"],
        ["Assigned", 8, "Naledi Dlamini", "dispatcher", "Assigned to Medical Support Two."],
      ]),
    },
    {
      id: "LIVE-20260804-1691",
      requesterId: "usr-requester-003",
      requesterName: "Zinhle Ncube",
      callbackNumber: "+27 84 555 0230",
      category: "Fire / smoke",
      severity: "Critical",
      note: "Smoke visible from a ground-floor shop. Occupancy is unknown.",
      status: "Received",
      createdAt: isoMinutesAgo(7),
      updatedAt: isoMinutesAgo(6),
      location: {
        address: "Bree Street, Johannesburg CBD",
        lat: -26.2046,
        lng: 28.0441,
        capturedAt: isoMinutesAgo(7),
        method: "Manual",
      },
      organisationId: "org-charlotte",
      operationalNotes: [],
      statusHistory: history("LIVE-20260804-1691", [
        ["Submitted", 7, "Zinhle Ncube", "requester"],
        ["Received", 6, "LIVE routing", "system", "Awaiting dispatcher assignment."],
      ]),
    },
    {
      id: "LIVE-20260804-1580",
      requesterId: "usr-requester-004",
      requesterName: "Rethabile Mokoena",
      callbackNumber: "+27 76 555 0288",
      category: "Personal safety",
      severity: "High",
      note: "Requester reports an immediate safety concern and needs assistance.",
      status: "Submitted",
      createdAt: isoMinutesAgo(3),
      updatedAt: isoMinutesAgo(3),
      location: {
        address: "Wits University East Campus, Johannesburg",
        lat: -26.1907,
        lng: 28.0301,
        accuracy: 22,
        capturedAt: isoMinutesAgo(3),
        method: "GPS",
      },
      operationalNotes: [],
      statusHistory: history("LIVE-20260804-1580", [["Submitted", 3, "Rethabile Mokoena", "requester"]]),
    },
    {
      id: "LIVE-20260803-1432",
      requesterId: "usr-requester-001",
      requesterName: "Thandi Mokoena",
      callbackNumber: "+27 82 555 0101",
      category: "Medical emergency",
      severity: "Moderate",
      note: "Minor injury after a fall. Patient required assessment.",
      status: "Closed",
      createdAt: isoMinutesAgo(24 * 60 + 90),
      updatedAt: isoMinutesAgo(24 * 60 + 20),
      location: {
        address: "Melville, Johannesburg",
        lat: -26.1758,
        lng: 28.0091,
        capturedAt: isoMinutesAgo(24 * 60 + 90),
        method: "Manual",
      },
      organisationId: "org-charlotte",
      assignedResponderId: "rsp-002",
      operationalNotes: ["Patient assessed and transported safely."],
      statusHistory: history("LIVE-20260803-1432", [
        ["Submitted", 24 * 60 + 90, "Thandi Mokoena", "requester"],
        ["Received", 24 * 60 + 88, "LIVE routing", "system"],
        ["Assigned", 24 * 60 + 80, "Naledi Dlamini", "dispatcher"],
        ["En route", 24 * 60 + 74, "Boitumelo Maseko", "responder"],
        ["Arrived", 24 * 60 + 55, "Boitumelo Maseko", "responder"],
        ["Closed", 24 * 60 + 20, "Naledi Dlamini", "dispatcher"],
      ]),
    },
    {
      id: "LIVE-20260802-1297",
      requesterId: "usr-requester-005",
      requesterName: "Neo Selemela",
      callbackNumber: "+27 78 555 0251",
      category: "Other urgent assistance",
      severity: "Moderate",
      note: "Assistance requested for an elderly person unable to stand.",
      status: "Cancelled",
      createdAt: isoMinutesAgo(2 * 24 * 60 + 40),
      updatedAt: isoMinutesAgo(2 * 24 * 60 + 31),
      location: {
        address: "Yeoville, Johannesburg",
        lat: -26.1849,
        lng: 28.0632,
        capturedAt: isoMinutesAgo(2 * 24 * 60 + 40),
        method: "Manual",
      },
      operationalNotes: ["Requester confirmed assistance was no longer required."],
      statusHistory: history("LIVE-20260802-1297", [
        ["Submitted", 2 * 24 * 60 + 40, "Neo Selemela", "requester"],
        ["Cancelled", 2 * 24 * 60 + 31, "Neo Selemela", "requester"],
      ]),
    },
  ];
}

function createAuditLogs(): AuditLog[] {
  return [
    {
      id: "log-001",
      actorName: "Kabelo Nkosi",
      actorRole: "responder",
      action: "Request status changed",
      target: "LIVE-20260804-1842",
      result: "Success",
      timestamp: isoMinutesAgo(10),
      correlationId: "corr-74d1f2",
      metadata: "Assigned → En route",
    },
    {
      id: "log-002",
      actorName: "Naledi Dlamini",
      actorRole: "dispatcher",
      action: "Responder assigned",
      target: "LIVE-20260804-1842",
      result: "Success",
      timestamp: isoMinutesAgo(13),
      correlationId: "corr-8a12c9",
      metadata: "Rapid Response Alpha / LIVE-21",
    },
    {
      id: "log-003",
      actorName: "LIVE routing",
      actorRole: "system",
      action: "Request routed",
      target: "LIVE-20260804-1691",
      result: "Success",
      timestamp: isoMinutesAgo(6),
      correlationId: "corr-1f5a33",
      metadata: "Internal dispatch dashboard",
    },
    {
      id: "log-004",
      actorName: "Unknown session",
      actorRole: "system",
      action: "Protected route access",
      target: "/api/admin/audit-logs",
      result: "Denied",
      timestamp: isoMinutesAgo(42),
      correlationId: "corr-bcc221",
      metadata: "Missing mock access token",
    },
    {
      id: "log-005",
      actorName: "Ayesha Patel",
      actorRole: "admin",
      action: "Organisation viewed",
      target: "org-charlotte",
      result: "Success",
      timestamp: isoMinutesAgo(70),
      correlationId: "corr-e0942a",
      metadata: "Administrative read",
    },
  ];
}

export function createInitialDatabase(): MockDatabase {
  const users: MockUser[] = MOCK_CREDENTIALS.map(({ password: _password, ...user }) => user);
  return {
    requests: createRequests(),
    notifications: [
      {
        id: "notification-001",
        userId: "usr-requester-001",
        title: "Responder is en route",
        message: "Rapid Response Alpha is travelling to your selected location.",
        requestId: "LIVE-20260804-1842",
        createdAt: isoMinutesAgo(10),
        read: false,
        tone: "success",
      },
      {
        id: "notification-002",
        userId: "usr-requester-001",
        title: "Request assigned",
        message: "Your request was assigned to Ambulance LIVE-21.",
        requestId: "LIVE-20260804-1842",
        createdAt: isoMinutesAgo(13),
        read: true,
        tone: "info",
      },
      {
        id: "notification-003",
        userId: "usr-requester-001",
        title: "Previous request completed",
        message: "Request LIVE-20260803-1432 was closed by the response team.",
        requestId: "LIVE-20260803-1432",
        createdAt: isoMinutesAgo(24 * 60 + 20),
        read: true,
        tone: "info",
      },
    ],
    users,
    organisations,
    responders,
    auditLogs: createAuditLogs(),
  };
}
