"use client";
import { Ambulance, MapPin, Power, Users } from "lucide-react";
import { useAuth } from "@/components/auth/auth-provider";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Panel, PanelHeader } from "@/components/ui/panel";
import { PageHeading } from "@/components/ui/page-heading";
import { PageSkeleton } from "@/components/ui/skeleton";
import { useMockStore } from "@/lib/mock-store";
export default function Resources(){const{user}=useAuth();const{db,loading,toggleResponderAvailability}=useMockStore();if(loading||!db||!user)return <PageSkeleton/>;return <div className="app-page grid gap-5"><PageHeading eyebrow="Dispatch" title="Response resources" description="View mock teams, vehicles and current roster availability."/><div className="grid gap-4 lg:grid-cols-2">{db.responders.map(r=>{const org=db.organisations.find(o=>o.id===r.organisationId);return <Panel key={r.id}><PanelHeader title={r.name} description={r.team} action={<Badge tone={r.availability==="Available"?"success":r.availability==="Assigned"?"warning":"slate"}>{r.availability}</Badge>}/><div className="divide-y divide-[#e2e8ed]"><div className="flex gap-3 p-4 sm:p-5"><Ambulance className="h-5 w-5 text-[#0f5b67]"/><div><p className="text-xs font-bold uppercase tracking-wide text-[#748693]">Vehicle</p><p className="mt-1 font-semibold">{r.vehicle}</p></div></div><div className="flex gap-3 p-4 sm:p-5"><Users className="h-5 w-5 text-[#0f5b67]"/><div><p className="text-xs font-bold uppercase tracking-wide text-[#748693]">Organisation</p><p className="mt-1 font-semibold">{org?.name}</p></div></div><div className="flex gap-3 p-4 sm:p-5"><MapPin className="h-5 w-5 text-[#0f5b67]"/><div><p className="text-xs font-bold uppercase tracking-wide text-[#748693]">Last mock position</p><p className="mt-1 font-semibold">{r.location.lat.toFixed(4)}, {r.location.lng.toFixed(4)}</p></div></div></div><div className="border-t border-[#e2e8ed] p-4"><Button variant="outline" className="w-full" disabled={r.availability==="Assigned"} onClick={()=>toggleResponderAvailability(r.id,user)}><Power className="h-4 w-4"/>{r.availability==="Available"?"Set offline":"Set available"}</Button></div></Panel>})}</div></div>}
